apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Spring Boot service scaffolded by Backstage
spec:
  type: service
  owner: ${{ values.owner }}
  lifecycle: experimental
