server:
  port: 8080

spring:
  application:
    name: ${{ values.name }}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.${{ values.organization }}.${{ values.name }}: DEBUG